version: 2

jobs:

  integrationTests:
    docker:
      - image: web3f/ci-commons:v3.1.6
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh kindest/node:v1.21.1

  deploy:
    docker:
      - image: web3f/ci-commons:v3.1.6
    resource_class: xlarge
    steps:
      - checkout
      - run:
          description: deploy to cluster
          environment:
            HELM_ENV: production
            CLUSTER: rbac-gcp
            GCP_REGION: europe-central2-a
            GCP_PROJECT: security-330311
            
          command: |
            chmod +x ./scripts/deploy.sh 
            ./scripts/deploy.sh 

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy:
          context: 
          - gcp_security_access
          - vault_security
          - argoCD
          - cloudflare
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
      