version: 2

jobs:
  helmLint:
    docker:
      - image: web3f/ci-commons:v3.0.0
    steps:
      - checkout
      - run:
          environment:
          
            HELM_ENV: production
            CLUSTER: rbac-gcp
            GCP_REGION: europe-central2-a
            GCP_PROJECT: security-330311
            
          command: |
            chmod +x ./scripts/deploy.sh 
            ./scripts/deploy.sh 

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - helmLint:
          context: gcp_security_access
          filters:
            tags:
              only: /.*/
      