environments:
  production:
  ci:
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
releases:
  - name: nginx-ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.0.19
    namespace: ingress-nginx
    values:
      - ./config/nginx-ingress-values.yaml.gotmpl
