environments:
  production:
  ci:
repositories:
  - name: argocd
    url: https://argoproj.github.io/argo-helm
releases:
  - name: argocd
    chart: argocd/argo-cd
    version: 3.35.3
    namespace: argocd
    values:
      - ./config/argocd-values.yaml.gotmpl
