environments:
  production:
  ci:
repositories:
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
releases:
  - name: vault-operator
    namespace: vault
    chart: banzaicloud-stable/vault-operator
    version: 1.15.7
    values:
      - ./config/bank-vault-values.yaml.gotmpl
