apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: previews
  namespace: argocd2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: appbundle-project-dev
  source:
    repoURL: https://github.com/vfarcic/argocd-previews.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: previews
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
